### ISSUE TITLE
Merging CSS rules with same properties fails in spec test

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-toolbox#819]
In the following spec test, you can see that there's two CSS rules that should have been merged together but weren't:

https://github.com/ampproject/amp-toolbox/blob/1cf9646b6723b4a3556356da02be190caacd1f32/packages/optimizer/spec/transformers/valid/ServerSideRendering/converts_sizes_attribute_to_css/expected_output.html#L8

A single rule `#i-amp-0,#i-amp-1{width:100vw}` should have been generated instead of the two separate rules `#i-amp-0{width:100vw}` & `#i-amp-1{width:100vw}`.

This currently causes a failure in the PHP library tests here: https://travis-ci.org/github/ampproject/amp-wp/jobs/693717928#L950-L951

**Comment by sebastianbenz** [comment]
I think I intentionally didn't merge these as the order in which the rules appear matters. 

For example:

```html
<amp-img id="img1" sizes="(max-width: 100px) 100px, 100vw"></amp-img>
<amp-img id="img2" sizes="(max-width: 100px) 100px, (max-width: 200px) 200px, 120vw"></amp-img>
```

The correct order is:

```css
#i-amp-1{width:100vw}
@media (max-width: 100px){ 
  #i-amp-1{width: 100px}
}

#i-amp-2{width:100vw}
/* max-width 200 needs to come before max-width 100 */
@media (max-width: 200px){ 
  #i-amp-2{width: 200px}
}
@media (max-width: 100px){ 
  #i-amp-2{width: 200px}
}
```

Merging rules would break the behavior by overwriting the implicit ordering semantics:

```css
#i-amp-1{width:100vw}
@media (max-width: 100px){ 
  /* this will never trigger for #i-amp-2 */
  #i-amp-1, #i-amp-2{width: 100px}
}

#i-amp-2{width:100vw}
@media (max-width: 200px){ 
  #i-amp-2{width: 200px}
}
```

Merging the default rules could work as these always need to come first. Not sure though if that's worth the effort and would be better handled via a CSS compressor.
